version: 2.1

orbs:
  sonar: hubci/sonar@0.3

workflows:
  main:
    jobs:
      - build:
          context: main-context

jobs:
  build:
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.14
      - run:
          name: "Build Docker Images"
          command: |
            # Fix hardcoded 'cimg' until CircleCI fixes this
            sed -i 's/cimg/hubci/g' build-images.sh
            sed -i 's/FROM cimg/FROM hubci/g' ./*/node/Dockerfile
            ./build-images.sh
      - sonar/install:
          version: 0.13.0
      - deploy:
          name: "Publish Docker Images (trunk branch only)"
          command: |
            if [ "${CIRCLE_BRANCH}" == "trunk" ]; then
              
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              
              # an else block will be added in the future for a staging release
              if git log -1 --pretty=%s | grep "\[release\]"; then
                echo "Publishing hubci/strawberry to Docker Hub production."
                docker push hubci/strawberry:0.18.0
                docker push hubci/strawberry:0.18
                docker push hubci/strawberry:0.18.0-node
                docker push hubci/strawberry:0.18-node
              else
                echo "Skipping publishing."
              fi

              # Update the Docker Hub description
              sonar set description hubci/strawberry ./README.md
            fi
